name: transform-feed
on:
  issue_comment:
    types: [created]
    
jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Fetch and transform feed
      run: make feed
      env:
        # Change these to match your own settings
        anchor-feed-url: https://anchor.fm/s/1f178454/podcast/rss
        anchor-username: oooxcast
        custom-base-url: https://oooxcast.fm

    - name: Clean your mess
      run: make rm-tmp
