name: transform-feed
on:
  issue_comment:
    types: [created]
    
jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Fetch and transform feed
      run: make feed
      env:
        # Change these to match your own settings
        anchor-feed-url: https://anchor.fm/s/1f178454/podcast/rss
        anchor-username: oooxcast
        custom-base-url: https://oooxcast.fm
        
    - name: Commit files
      run: |
        git config --local user.email "action@github.com"
        git config --local user.name "GitHub Action"
        git add feed.xml feed.json
        git commit -am "Updated feed"
        
    - name: Push changes
      uses: ad-m/github-push-action@master
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        force: true
