name: transform-feed
on:
  issue_comment:
    types: [created]
  repository_dispatch:
        types: [build]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Validate comment and issue number
      if: ${{ github.event.comment.body != 'build' || github.event.issue.number != 1 }}
      run: make phony-error

    - name: Validate comment and issue number
      if: ${{ !secrets.ANCHOR_USERNAME || !secrets.SITE_BASE }}
      run: make phony-error

    - name: Add start reaction
      uses: peter-evans/create-or-update-comment@v1
      with:
        comment-id: ${{ github.event.comment.id }}
        reactions: eyes

    - name: Install deps
      run: make install

    - name: Fetch and parse feed
      run: make feed username=${{ secrets.ANCHOR_USERNAME }} site-base=${{ secrets.SITE_BASE }}

    - name: Feed to json
      run: make transform

    - name: Commit files
      run: |
        git config --local user.email "action@github.com"
        git config --local user.name "Github Actions"
        git add public/
        git commit -am ":loudspeaker: Feed update requested by ${{ github.event.comment.user.login }}"

    - name: Push changes
      uses: ad-m/github-push-action@master
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        force: true
        branch: gh-pages

    - name: Add success reaction
      uses: peter-evans/create-or-update-comment@v1
      if: ${{ success() }}
      with:
        comment-id: ${{ github.event.comment.id }}
        reactions: heart

    - name: Add fail comment when secrets are missing
      uses: peter-evans/create-or-update-comment@v1
      if: ${{ !secrets.ANCHOR_USERNAME || !secrets.SITE_BASE }}
      with:
        comment-id: ${{ github.event.comment.id }}
	body: |
	      Required secrets **ANCHOR_USERNAME** and **SITE_BASE** are not set.
	      Please refer the docs.


    - name: Add generic fail reaction
      uses: peter-evans/create-or-update-comment@v1
      # Send fail responses only on issue number 1
      if: ${{ failure() && github.event.issue.number == 1 }}
      with:
        comment-id: ${{ github.event.comment.id }}
        reactions: -1
